---
# tasks file for nvm
# vim: noai:ts=2:sw=2:expandtab
- name: Install curl
  apt: name=curl state=present

- name: Download nvm
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/{{nvm_version}}/install.sh dest=/home/{{ user }}/nvm-install.sh  owner={{ user }} group={{ user }} mode=0755
  environment: proxy_env

- name: Install nvm
  shell: /home/{{ user }}/nvm-install.sh chdir=/home/{{user}} creates=/home/{{ user }}/.gvm
  sudo: yes
  sudo_user: "{{ user }}"
  environment: proxy_env
