---
# tasks file for nvm
# vim: noai:ts=2:sw=2:expandtab
- name: Install nvm
  shell: curl https://raw.githubusercontent.com/creationix/nvm/{{nvm_version}}/install.sh | bash
  args:
    creates: /home/{{ user }}/.nvm
  sudo: yes
  sudo_user: {{ user }}
