# vim: noai:ts=4:sw=4:expandtab
---
# file dev
- hosts: localhost
  pre_tasks:
    - name: Create user
      user: name={{ user }} password="$6$kewG32Frb1Ei/$f.0k8A0N9.04.jwd/ekddXWq56BBTG7V/jwSPgJeY8kfEAJNkqgErIn/knDpSDcm/gcvKnOBQcjdosNkyrO.t0"
  roles:
    - dev-tools
    - {role: wybczu.oracle_jdk, oracle_jdk_version: 8u20-b26 }
    - {role: maven, version: 3.2.3, oracle_jdk_not_default: true}
    - {role: eclipse-luna }
    - {role: wildfly, version: 8.2.0.Final }
    - {role: glassfish, version: 4.1 }
#    - {role: glassfish, version: "4.1" }
    - devbox.chrome
    - azavea.fig

  vars:
    oracle_jdk_version: 8u20-b26
    user: richard
    password: dMp7H.LtCccmU
