# vim: noai:ts=4:sw=4:expandtab
---
# file dev
- hosts: localhost
  roles:
    - dev-tools
    - {role: wybczu.oracle_jdk, oracle_jdk_version: 8u20-b26 }
    - {role: tomcat8, version: 8.0.14}
    - {role: maven, version: 3.2.3}
    - {role: intellij, version: 13.1.3, build: 135.909}
    - gvm
    - devbox.chrome
    - nvm

