# vim: noai:ts=4:sw=4:expandtab
---
# file dev
- hosts: localhost
  pre_tasks:
    - name: Create user
      user: name={{ user }} password="$6$kewG32Frb1Ei/$f.0k8A0N9.04.jwd/ekddXWq56BBTG7V/jwSPgJeY8kfEAJNkqgErIn/knDpSDcm/gcvKnOBQcjdosNkyrO.t0"
  roles:
    - dev-tools
    - {role: wybczu.oracle_jdk, oracle_jdk_version: 8u20-b26 }
    - {role: maven, version: 3.2.5, oracle_jdk_not_default: true}
    - devbox.chrome
    - azavea.fig
    - nvm
    - gvm
    - angstwad.docker_ubuntu
    - intellij
    - {role: tomcat8, version: 8.0.18 }

  vars:
    oracle_jdk_version: 8u20-b26
    user: richard
    password: dMp7H.LtCccmU
    docker_version: 1.4.1
