---

oracle_jvm_location: "/usr/lib/jvm"

oracle_jdk_arch:
  x86_64: x64
  i386: i586

oracle_jdk_location: "{{ oracle_jvm_location }}/java-{{ oracle_jdk_version[0] }}-oracle-{{ oracle_jdk_version }}"
oracle_jdk_archive: "jdk-{{ oracle_jdk_version.split('-')[0] }}-linux-{{ oracle_jdk_arch[ansible_architecture] }}.tar.gz"
oracle_jdk_default_link: "{{ oracle_jvm_location }}/java-{{ oracle_jdk_version[0] }}-oracle"

oracle_jdk_tools:
  - appletviewer
  - extcheck
  - idlj
  - jar
  - jarsigner
  - javac
  - javadoc
  - javah
  - javap
  - jconsole
  - jdb
  - jhat
  - jinfo
  - jmap
  - jmc
  - jps
  - jrunscript
  - jsadebugd
  - jstack
  - jstat
  - jstatd
  - native2ascii
  - rmic
  - schemagen
  - serialver
  - wsgen
  - wsimport
  - xjc

oracle_jdk_jre_tools:
  - java
  - keytool
  - pack200
  - rmid
  - rmiregistry
  - unpack200
  - orbd
  - servertool
  - tnameserv
