# vim: noai:ts=2:sw=2:expandtab
---
- name: Download Apache Maven
  get_url: url=http://www.eu.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz dest=/opt/apache-maven-{{ maven_version }}.tar.gz
  environment: proxy_env

- name: Create apache-maven directory
  command: mkdir /opt/apache-maven creates=/opt/apache-maven

- name: Remove current link
  command: rm -rf /opt/apache-maven/current

- name: Extract archive
  command: /bin/tar xvf /opt/apache-maven-{{ maven_version }}.tar.gz -C /opt/apache-maven creates=/opt/apache-maven/apache-maven-{{ maven_version }}

- name: Change ownership of Maven installation
  file: path=/opt/apache-maven-{{ maven_version }} owner={{ user }} group={{ user }} state=directory recurse=yes

- name: Create symlink
  command: chdir=/opt/apache-maven ln -s apache-maven-{{ maven_version }} current
  
