# vim: noai:ts=2:sw=2:expandtab
---
  - apt: name=git
  - apt: name=git-flow
  - apt: name=gitk
  - apt: name=meld
  - apt: name=jardiff
  - apt: name=language-pack-de
  - apt: name=vim
  - apt: name=vim-addon-manager
  - apt: name=vim-python-jedi
  - apt: name=vim-syntax-docker
  - apt: name=vim-youcompleteme
  - apt: name=emacs
