# vim: noai:ts=2:sw=2:expandtab
---
- name: Install curl
  apt: name=curl state=present

- name: Install gvm
  shell: curl -s get.gvmtool.net | bash
  args: 
    chdir: /home/{{ user }}
    creates: /home/{{ user }}/.gvm

- name: Change ownership of gvm installation
  file: path=/home/{{ user }}/.gvm owner={{ user }} group={{ user }} state=directory recurse=yes


