# vim: noai:ts=2:sw=2:expandtab
---
- name: Install curl
  apt: name=curl state=present

- name: Install gvm
  shell: curl -s get.gvmtool.net | bash
  args: 
    chdir: /home/dev
    creates: /home/dev/.gvm

- name: Change ownership of gvm installation
  file: path=/home/dev/.gvm owner=dev group=dev state=directory recurse=yes


