# vim: noai:ts=2:sw=2:expandtab
---
- name: Install curl
  apt: name=curl state=present

- name: Download gvm
  get_url: url=http://get.gvmtool.net dest=/home/{{ user }}/gvm-tool.sh owner={{ user }} group={{ user }}
  environment: proxy_env

- name: Change mode
  file: path=/home/{{ user }}/gvm-tool.sh mode=0755

- name: Install gvm
  shell: /home/{{ user }}/gvm-tool.sh chdir=/home/{{user}} creates=/home/{{ user }}/.gvm
  sudo: yes
  sudo_user: "{{ user }}"
  environment: proxy_env

- name: Change ownership of gvm installation
  file: path=/home/{{ user }}/.gvm owner={{ user }} group={{ user }} state=directory recurse=yes


