# vim: noai:ts=2:sw=2:expandtab
---
- name: Install Java 1.7
  apt: name=openjdk-7-jdk state=present

- name: Download STS, using curl because of timeout
  command: curl http://download.springsource.com/release/STS/{{sts_version}}/dist/e{{eclipse_version}}/spring-tool-suite-{{sts_version}}.RELEASE-e{{eclipse_full_version}}-linux-gtk-x86_64.tar.gz  > /opt/sts-{{sts_version}}.tar.gz 

- name: Create sts directory
  command: mkdir /opt/sts creates=/opt/sts

- name: Remove current link
  command: rm -rf /opt/sts/current
#
#- name: Extract archive
#  command: /bin/tar xvf /opt/sts-{{sts_version}}.tar.gz -C /opt/sts creates=/opt/sts/sts-{{version}}
#
#- name: Create symlink
#  command: chdir=/opt/apache-tomcat ln -s apache-tomcat-{{version}} current
#
#- name: Change ownership of Tomcat installation
#  file: path=/opt/apache-tomcat owner=dev group=dev state=directory recurse=yes

  
